### ISSUE TITLE
Domänenmodell Iteration

### ISSUE THREAD

**Issue by Felix2019** [Felix2019/WebNASA#15]

**Comment by Felix2019** [comment]
Weitere Iteration des Domänenmodells ist nötig.

**Comment by CCB-Git** [comment]
<img width="1109" alt="Domänenmodell_Roboter" src="https://user-images.githubusercontent.com/44359333/57301098-7afa9480-70d8-11e9-8d1b-cdffd2146b6b.png">

**Comment by Felix2019** [comment]
<img width="1878" alt="lol" src="https://user-images.githubusercontent.com/41749089/57445693-39422900-7253-11e9-9be1-cc90d5bd358c.png">

**Comment by Felix2019** [comment]
<img width="2816" alt="Domänenmodell_V1" src="https://user-images.githubusercontent.com/41749089/57445760-537c0700-7253-11e9-81d7-ef210a377f43.png">
