### ISSUE TITLE
Domänenmodel 

### ISSUE THREAD

**Issue by Marius998** [Felix2019/WebNASA#7]

**Comment by CCB-Git** [comment]
[Domänenmodell](https://github.com/Felix2019/WebNASA/files/3114241/Gescanntes.Dokument.pdf)

**Comment by CCB-Git** [comment]
<img width="1037" alt="Domänenmodell" src="https://user-images.githubusercontent.com/44359333/56695539-a13c2f80-66e9-11e9-9290-6545d6492be8.png">

**Comment by CCB-Git** [comment]
Vorerst als aktuelles Domänenmodell abgeschlossen, spätere Iterationen selbstverständlich möglich.
